feat: Added admin donation filter buttos
uwblueprint/community-fridge-kw pull request #196
Opened 2022-04-08 03:36 UTC by AmandaMisjuwar

## Brief description. What is this change? 

### [Create Admin Scheduled Donations Filter Views and Buttons](https://www.notion.so/uwblueprintexecs/Create-Admin-Scheduled-Donations-Filter-Views-and-Buttons-40949fd284da4adfb74b0e31c0a70634)

## Implementation description. How did you make this change?
* Added admin donation views export and filter buttons
* Added frontend filter functionality for admin donation view (gets all donations on first render and filter on FE)
* Fixed mobile + desktop spacing for donation and check in views

## Steps to test
1. Create two donations 
2. Create a volunteer account
3. Use PG Admin to assign a volunteer to one of the two donations by editing directly when viewing the table 
4. Log in as an admin
5. Go to Fridge Management > Scheduled Donations
6. All scheduled donations should show as default filter is All
7. Select filter by Filled
8. Only the scheduled donation with the assigned volunteer should show
9. Select filter by Unassigned
10. Only the scheduled donation with no assigned volunteers should show
11. Make sure mobile + desktop matches designs and check for the Check-In view as well

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages follow conventional commits and are descriptive. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s) 
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [ ] The appropriate tests if necessary have been written

2022-04-08 03:42 UTC, AmandaMisjuwar commented
I spent almost 1 hr trying to fix spacing to find the only thing i needed was `width=100%` D:<

2022-04-10 00:28 UTC, hanlinc27 requested changes
functionality seems to work for me! just a quick comment 💯

2022-04-10 00:28 UTC, hanlinc27 commented on frontend/src/components/pages/AdminDashboard/ViewDonationsAndCheckIns.tsx
> +  }, [selectedFilter]);
can we memoize this?
```suggestion
  React.useMemo(()=>{
    if (selectedFilter === DonationFilterType.FILLED){
      setFilteredSchedules([...schedules.filter((schedule) => schedule.volunteerId != null)]);
    }
    else if (selectedFilter === DonationFilterType.UNASSIGNED){
      setFilteredSchedules([...schedules.filter((schedule) => schedule.volunteerId == null)]);
    }
    else {
      setFilteredSchedules([...schedules]);
    }
  }, [selectedFilter]);
```

2022-04-10 00:28 UTC, hanlinc27 commented on frontend/src/components/pages/AdminDashboard/ViewDonationsAndCheckIns.tsx
> +              borderColor={isMobile ? "none" : "dorian.100"}
```suggestion
              background={["dorian.100","none"]}
              border={["none" : "1px"]}
              borderColor={["none" : "dorian.100]}
```

2022-04-10 00:28 UTC, hanlinc27 commented on frontend/src/components/pages/AdminDashboard/ViewDonationsAndCheckIns.tsx
> +              flex={isMobile ? 1.5 : 2.5}
```suggestion
              flex={[1.5,2.5]}

```

2022-04-10 03:01 UTC, hanlinc27 approved these changes

2022-04-10 03:15 UTC, merged