feat: admin export food rescues and checkins
uwblueprint/community-fridge-kw pull request #203
Opened 2022-04-11 06:10 UTC by Shehryar21

## Brief description. What is this change? 

### [Admin Export All Fridge Check-ins/Food Rescues](https://www.notion.so/uwblueprintexecs/Admin-Export-All-Fridge-Check-ins-Food-Rescues-262515bd7cbe43ceb5111eb9066c8567)

## Implementation description. How did you make this change?
* Added `generateCSV` utils file back which we deleted once a while ago

## Steps to test
1. Create some checkins and schedules
2. Go to http://localhost:3000/admin/check-ins and click on export. It should download a csv file. Verify that the data outputted in the csv file is accurate.
3. Go to http://localhost:3000/admin/view-donations and click on export. It should download a csv file. Verify that the data outputted in the csv file is accurate.

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages follow conventional commits and are descriptive. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s) 
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [ ] The appropriate tests if necessary have been written

2022-04-14 20:58 UTC, hanlinc27 requested changes
Functionality works for me. From the admin's perspective, these dates are pretty hard to read - can we format this properly when it's being mapped in `getCSVData`?
<img width="554" alt="Screen Shot 2022-04-14 at 4 36 33 PM" src="https://user-images.githubusercontent.com/19617248/163473442-d134a0e4-827b-472e-a3e2-c4998f3ecf2a.png">

also two other questions
1. Should we be fetching _all_ checkins/schedules or just upcoming?
2. Is it worth it to semi optimize the fetching function to store volunteerId and donorId's in a hashmap or something so that we're not fetching it from the backend for every single entry?

2022-04-14 20:58 UTC, hanlinc27 commented on frontend/src/components/pages/AdminDashboard/ViewDonationsAndCheckIns.tsx
> +  };
nit: why don't we keep this function inside of `CSVUtils` and expose a parameter to download the correct checkin/scheduling csv?

2022-04-14 20:58 UTC, hanlinc27 commented on frontend/src/components/pages/AdminDashboard/getCSVData.tsx
> +          schedule.volunteerId!.toString(),
```suggestion
          schedule.volunteerId.toString(),
```

2022-04-14 23:11 UTC, Shehryar21 commented
> Functionality works for me. From the admin's perspective, these dates are pretty hard to read - can we format this properly when it's being mapped in `getCSVData`? <img alt="Screen Shot 2022-04-14 at 4 36 33 PM" width="554" src="https://user-images.githubusercontent.com/19617248/163473442-d134a0e4-827b-472e-a3e2-c4998f3ecf2a.png">
> 
> also two other questions
> 
> 1. Should we be fetching _all_ checkins/schedules or just upcoming?
> 2. Is it worth it to semi optimize the fetching function to store volunteerId and donorId's in a hashmap or something so that we're not fetching it from the backend for every single entry?

1) We should be fetching all (confirmed with Amy)
2) tbh dont think its necessary. Given that fetching only happens on export, it wont happen that often anyways.

2022-04-15 01:51 UTC, hanlinc27 approved these changes

2022-04-15 01:57 UTC, merged