feat: add email when admin removes volunteer from checkin
uwblueprint/community-fridge-kw pull request #230
Opened 2022-04-17 21:10 UTC by Shehryar21

## Brief description. What is this change? 

## Implementation description. How did you make this change?
* When admin removes volunteer from checkin, the volunteer should get an email

## Steps to test
1. Sign up for a fridge checkin shift as a volunteer. Make sure you get a confirmation email for checkin sign up. Admin should get one as well. If you want to test for admin, you can change the email in getAdmin() function locally to make sure admin is getting the email
2. Cancel your fridge checkin shift and make sure you get a cancellation email. Admin should also get a cancellation email
3. Sign in as admin. Remove the volunteer from the shift. The volunteer should get a cancellation email
4. As an admin, assign yourself as admin and make sure no one gets any email and there are no errors
5. As an admin, Remove yourself from volunteer shift, and make sure no one gets any email and there are no errors

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages follow conventional commits and are descriptive. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s) 
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [ ] The appropriate tests if necessary have been written

2022-04-18 01:32 UTC, AmandaMisjuwar requested changes

2022-04-18 23:51 UTC, Shehryar21 commented on backend/typescript/services/implementations/checkInService.ts
> +      );
actually i just realized there is difference if i use that function. It doesnt have the apologize line, and i dont think the checkin copy had view Dashboard link

2022-04-19 00:23 UTC, AmandaMisjuwar commented on backend/typescript/services/implementations/checkInService.ts
> +      );
Oh what, I think I used that function and it includes the apologize line. But yeah I guess if it works this way then it's fine!

2022-04-21 01:33 UTC, AmandaMisjuwar approved these changes
I edited call to `cancellationEmail` to include apology section of email, and everything else worked for me!

2022-04-21 03:12 UTC, merged