feat: add empty state to calendar
uwblueprint/community-fridge-kw pull request #231
Opened 2022-04-18 23:53 UTC by carissa-tang

## Brief description. What is this change? 

### [Add “empty state” for calendar](https://www.notion.so/uwblueprintexecs/Add-empty-state-for-calendar-d6d698bfcdd744918d4ab29d32ba9759)

## Implementation description. How did you make this change?
* Waiting for design

## Steps to test
1.

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages follow conventional commits and are descriptive. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s) 
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [ ] The appropriate tests if necessary have been written

2022-04-21 23:25 UTC, hanlinc27 requested changes

2022-04-21 23:25 UTC, hanlinc27 commented on frontend/src/components/common/Calendar/WeeklyCalendar.tsx
> +    : shiftsArr.map((item, index) => {
I'm seeing this crash consistently on this branch: 
![image](https://user-images.githubusercontent.com/19617248/164566877-fa7473de-470b-4df5-b096-2c4ab02ff5b4.png)

![image](https://user-images.githubusercontent.com/19617248/164566792-1efcf294-2e2e-451a-8967-3eb4ba7ccc05.png)

2022-04-22 17:01 UTC, carissa-tang commented on frontend/src/components/common/Footer.tsx
> +    <Divider pt={{ base: "79px", md: "117px" }} />
revert change in my previous PR that made the spacing of all other pages off

2022-04-24 16:17 UTC, jessiiepeng approved these changes
the empty states work on my side for desktop / mobile!

2022-04-24 18:34 UTC, Shehryar21 approved these changes
Checked on staging and was working

2022-04-24 19:04 UTC, xsharonhe approved these changes
worked for me just made a small wording change on main calendar page

2022-04-25 03:34 UTC, hanlinc27 approved these changes

2022-04-25 03:39 UTC, merged